spring:
  application:
    name: config
  profiles:
    active: native #如果使用本地仓库集合吧设置为native
  cloud:
    config:
      server:
        native: #这里只能叫config要不然找不到,可以替换成git的远程仓库的方式，方便版本管理，远程仓库以config-repo- 开头
          search-locations: classpath:/config
eureka:
  client:
    service-url:
      defaultZone: http://172.31.84.138:8761/eureka/
  instance:
    ip-address: 172.31.84.138 #这里是我的容器所在服务器的地址
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 9000
