server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qaz123456.
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8&useSSL=false
snowFlakeIdGenerator:
  workerId: 0
  dataCenterId: 0
# 默认之配置为TM的本机默认端口
tx-lcn:
  client:
    manager-address: 172.31.84.138:8070
  logger:
    enabled: true
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tx-manager?characterEncoding=UTF-8
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}