server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gxy123456.
    url: jdbc:mysql://127.0.0.1:3306/store?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
snowFlakeIdGenerator:
  workerId: 1
  dataCenterId: 1
feign:
  hystrix:
    enabled: true #开启hystrix进行熔断保护
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL