server:
  port: 9003
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qaz123456.
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false
logging:
  level:
    com.gxy.user.mapper: DEBUG
snowFlakeIdGenerator:
  workerId: 2
  dataCenterId: 2