#Eureka配置详细地址:
spring:
  application:
    name: center
server:
  port: 8761
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: register-center
    ip-address: 127.0.0.1
    #可以在你鼠标放在eureka里面查看时左下角会显示你的ip地址
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${eureka.instance.ip-address}:${server.port}
  #服务注册类配置
  client:
    service-url:
      #指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka ，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
      #如果服务注册中心加入了安全验证，这里配置的地址格式为： http://<username>:<password>@localhost:8761/eureka 其中 <username> 为安全校验的用户名；<password> 为该用户的密码
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true,高可用时为true
    fetch-registry: false
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true,eureka server可以设为false
    register-with-eureka: false
  server:
    #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，
    #如果关闭,服务注册中心将不可用的实例正确剔除,开发环境关闭
    enable-self-preservation: false

